name: dash_bubble_local
description: "Floating Bubble overlay service (local clone)"
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
