name: mirror_scorpion_v2
description: "Mirror Scorpion - حيث تُصنع البدايات"
publish_to: 'none'
version: 1.2.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  google_mlkit_text_recognition: ^0.13.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.2.1
  shared_preferences: ^2.3.3
  path_provider: ^2.1.4
  flutter_tts: ^3.8.5
  sqflite: ^2.3.3+1
  intl: ^0.20.2
  permission_handler: ^11.3.1
  speech_to_text: 6.6.2
  file_picker: ^8.3.7
  image_picker: ^1.1.2
  clipboard: ^0.1.3
  share_plus: ^10.1.4
  url_launcher: ^6.3.1
  sensors_plus: ^6.1.1
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/hadiths.json
    - assets/data/hadith_qudsi.json
    - assets/data/quran_stories.json
    - assets/data/stories.json
    - assets/data/asbab_nuzul.json
    - assets/data/arbaeen_nawawi.json
    - assets/data/prophet_stories_ibn_kathir.json
    - assets/images/
