name: speech_to_text
description: "A Flutter plugin that exposes device specific speech to text recognition capability."
version: 7.4.0
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  speech_to_text_platform_interface: ^2.4.0
  json_annotation: ^4.0.0
  clock: ^1.0.1
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.1.7
  web: ^1.0.0
  speech_to_text_windows: ^1.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.csdcorp.speech_to_text
        pluginClass: SpeechToTextPlugin
      ios:
        pluginClass: SpeechToTextPlugin
        sharedDarwinSource: true
      web:
        pluginClass: SpeechToTextPlugin
        fileName: speech_to_text_web.dart
      macos:
        pluginClass: SpeechToTextPlugin
        sharedDarwinSource: true
      windows:
        default_package: speech_to_text_windows
